fix(frontend): remove alias check (#7562)
In the old version, we guarantee every column with a alias name, these behaviour caused the bug #7549.

### And why we have this guarantee:
At that time, function didn't have a alias, to guarantee every function column have a column name, we enforce the user must specify column alias.(A rude solution) https://github.com/risingwavelabs/risingwave/pull/6798

But now, we can derive function alias so that I think we can remove the alias check.

After remove it, our behaviour will be compatiable with postgres:

```
test_db=> create table t1 as select 1;
SELECT 1
test_db=> select * from t1;
?column?
----------
1
(1 row)

test_db=> create table t as select 1,2,3;
ERROR:  column "?column?" specified more than once

test_db=> create table t as select 1 as a , 2 as b;
SELECT 1
test_db=> select * from t;
a | b
---+---
1 | 2
(1 row)

```

Approved-By: st1page