feat(now): implement `now()` in batch (#7161)
Enable batch system to evaluate `NOW()` as a function instead of an operator.
result before this PR:
```
dev=> select now();
ERROR:  QueryError: internal error: Failed to build executor: Expr error: Unsupported function: Ok(Now)
```
result after this PR:
test result:
```
dev=> select now();
?column?
----------------------------
2023-01-03 08:01:52.304273
(1 row)

dev=> create table t (v1 int);
CREATE_TABLE
dev=> create materialized view mv as select now() as nw from t where v1 >= 3;
ERROR:  QueryError: internal error: Rpc error: gRPC error (Internal error): Expression error: Expected session timestamp bound into Now
dev=> create table tt(v1 int, t1 timestamp);
CREATE_TABLE
dev=> create materialized view mv as select * from tt where tt.t1 > now() - INTERVAL '1 hour';
CREATE_MATERIALIZED_VIEW
```
We insert a session timestamp into arguments of `NOW()`, which will only be used in batch system.

Approved-By: chenzl25
Approved-By: fuyufjh
Approved-By: jon-chuang

Co-Authored-By: Liang Zhao <liang@singularity-data.com>
Co-Authored-By: Eric Fu <eric@singularity-data.com>