feat(frontend): support struct cast (#6552)
This PR adds support for struct casting and passes all struct tests from duckdb plus our new tests.

The implementation is like we convert the existing type into an enum { Infer, Type, Struct }, and then use implicit cast rules to infer the correct cast type.

* If both left and right are concrete struct types (i.e. in schema, not row expression), recursively resolve two types.
* If either side is concrete struct type and the other side is row expression, recursively resolve one type and one expression.
* If both sides are row expression, recursively resolve two expressions.
* The base case: we've got two type|expression, and we match them.

The cast is not the same as Postgres. I feel Postgres's struct casting is too restrictive and users might not like it. For example, all of the following queries will error in Postgres:

```
?=> create type t3 as (v1 int, v2 int);
CREATE TYPE
?=> create type t4 as (v1 varchar, v2 varchar);
CREATE TYPE
?=> create table t5(v1 t3, v2 t4);
CREATE TABLE
?=> insert into t5 values (row(1, 1), row(1, 1));
INSERT 0 1

select v1 = v2 from t5;
ERROR:  cannot compare dissimilar column types integer and character varying at record column 1
select v1 = row('1', '1') from t5;
ERROR:  cannot compare dissimilar column types integer and unknown at record column 1
select v2 = row('1', '1') from t5;
ERROR:  cannot compare dissimilar column types character varying and unknown at record column 1
select v2 = row(1, 1) from t5;
ERROR:  cannot compare dissimilar column types character varying and integer at record column 1
```

Therefore, we took a different approach (comments welcomed): if we can assign one field to another, we will do the cast. This makes the struct type more flexible.

The code might need some refactors if we can finalize the struct comparison approach in RisingWave. If we allow implicit assign casts, the logic can be greatly simplified.


Approved-By: xiangjinwu

Co-Authored-By: Bugen Zhao <i@bugenzhao.com>
Co-Authored-By: Xiangjin <xiangjin@singularity-data.com>